### PR TITLE
lab: checklist items for lab8

### PR DESCRIPTION
**Pull request by umitcan07**
Main Topics To Discuss & Document:

- Primary features
- Domain-specific features
- API and its documentation
- Standard(s) being followed
- Testing strategies

### CODE REVIEW

**Comment by umitcan07** [comment]
I'll let responsible people leave a comment for each bullet point below

👇👇👇👇

**Comment by ArdaVural** [comment]
### Testing Strategies
1.

**Comment by umitcan07** [comment]
## Testing Strategies

### Web  

@umitcan07 @hks1444  

We will continue using [Vitest](https://vitest.dev/) as our primary framework for unit testing and will extend its use to integration testing as well. Additionally, we will incorporate [Playwright](https://playwright.dev/) for integration and end-to-end (E2E) testing to simulate real-world user interactions.

Unit tests will focus on runtime TypeScript functions that have no external dependencies. Integration tests will validate the behavior of features and components in conjunction with APIs and browser environments. End-to-end tests will ensure that full application flows, such as navigating through pages or completing quizzes, function as expected under simulated user conditions.

#### **Unit Tests**

We have selected **Vitest** because it integrates seamlessly with our existing **Vite** setup, offering excellent performance and an intuitive API. It’s particularly well-suited for testing isolated utility functions in a clean and efficient manner.

Current unit tests are located in `./client/src/tests/` but will be migrated to `./client/src/tests/unit` for better organization.  

**Acceptance Criteria:**

- [ ] Unit tests are written for all new utility functions introduced with features.
- [ ] All unit tests are moved to `./client/src/tests/unit`.

#### **Integration & End-to-End Tests**

We will leverage **Playwright** for integration and E2E testing. Its ability to emulate various browsers and environments makes it ideal for testing the interaction of components, API integrations, and user workflows. By simulating user behavior, we can validate the robustness of features such as quizzes, forum posts, and user profiles.
We will focus on the component-level testing, ensuring that each feature behaves as expected under different scenarios. This includes testing for rendering, props, and state management.

Since we are no longer using [MSW](https://mswjs.io/) for API mocking, we will need to update our Playwright tests to use the `fetch` API directly. This will allow us to simulate API responses and ensure that our application functions as expected.

Integration and end-to-end tests are currently located under `./client/src/tests`. In the future, integration tests will be moved to `./client/src/tests/integration`.

**Acceptance Criteria:**

- [ ] Each key route and feature (e.g., **Profile**, **Quizzes**, **Quiz**, **Forum**) has at least one integration test.
- [ ] Integration tests are moved to `./client/src/tests/integration`.
- [ ] At least one end-to-end test validates a complete user workflow for critical application features.

**Comment by hks1444** [comment]
### [Standards Being Followed](https://github.com/bounswe/bounswe2024group11/wiki/Lab8-Standards)

@umitcan07 @hks1444  
You can see the the pictures showing standards [here](https://github.com/bounswe/bounswe2024group11/wiki/Lab8-Standards/_edit)

#### [WAI-ARIA](https://github.com/bounswe/bounswe2024group11/wiki/Standards:-WAI%E2%80%90ARIA-1.2-Standards)
Given the application's rich functionality and numerous features, adhering to WAI-ARIA standards was essential. We selected ARIA attributes to ensure accessibility, as outlined in our Wiki page. Additionally, we utilized a headless component library, [Ariakit](https://ariakit.org/), which is designed with accessibility in mind. This allowed us to efficiently implement complex components such as hovercards and comboboxes, streamlining development while ensuring the application remains accessible.

#### [WCAG](https://github.com/bounswe/bounswe2024group11/wiki/Standards:-WCAG-2.1-Standards)

To accommodate both static content and user-generated content within the application, we followed WCAG guidelines and incorporated appropriate tags as detailed in our Wiki documentation. During code reviews, we actively identified and addressed issues related to missing or incorrect tag usage to maintain compliance and accessibility standards.

#### [SVG](https://github.com/bounswe/bounswe2024group11/wiki/Standards:-SVG-2-Accessibility-Standards)

We added meaningful `title` attributes to SVG illustrations used in various sections, such as the error state, new forum question page, and start quiz page. These titles include clear and well-defined descriptions to enhance accessibility and provide context for assistive technologies.

Since we mostly upheld the standards up to this point, only minor fixes for the existing features are required. However, we must keep complying to the standards while adding new features.

#### Acceptance Criteria

- [ ] Detect components not adhering the standards and fix them.
- [ ] Make sure the newly added components adhere to the standards before merging them to the main branch.

**Comment by ceydanursen** [comment]
[API and its documentation](https://github.com/bounswe/bounswe2024group11/wiki/API--Documentation) can be seen here. The examples for the API can be accessed from the swagger in the documentation

#### Acceptance Criteria

- [ ] Every API implemented should have the swagger documentation. 
- [ ] Swagger documentation should demonstrate the example response, results and the corrosponding errors for each endpoint .

**Comment by ozankrkya** [comment]
Primary Features implemented in the current phase is documented [here](https://github.com/bounswe/bounswe2024group11/wiki/Primary-Features-of-Turquiz). 

Please note that all of the features and examples are in the status of completed in the document.

**Pull request merged**
