### PR TITLE
feat(client): implement login page and routing

### PR DESCRIPTION
**Pull request by hks1444**
Implemented login route and created corresponding route on the mockup server
username: hasan
password: umitcan

### CODE REVIEW

**Review by umitcan07 — CHANGES_REQUESTED** [review]
rebase please

**Comment by hks1444** [comment]
@umitcan07 

> rebase please

It was an oversight on my part.

**Comment by umitcan07** [comment]
@hks1444 Can you also

`git fetch`
`git checkout development`
`git pull`
`git checkout -` => Returns you to this branch back. if it doesn't work `git checkout implement-login-route`
`git rebase origin/development`

**Comment by umitcan07** [comment]
the files changes says 36!!
you've only changed a few in this pr. makes it harder to catch up.
please make sure to pull the latest dev / main changes before you create another branch off of them.

**Comment by hks1444** [comment]
Sorry. The rebaseing was too intricate and I couldn't do myself. The first nine commits were already merged. Can you only check [this](https://github.com/bounswe/bounswe2024group11/pull/508/commits/467779c02c97ca2867883e799cb705ff59fb31d2)? This is the only thing changed.

**Comment by hks1444** [comment]
> the files changes says 36!! you've only changed a few in this pr. makes it harder to catch up. please make sure to pull the latest dev / main changes before you create another branch off of them.

Now its 11. I am not sure if I did the rebasing correctly but it seems like it worked.

**Comment by umitcan07** [comment]
let's use better PR names.
using conventional commits.
any PRs into `development` are gonna be squashed and the name of the resulting commit will be the pr title.

for  PRs from `development` to `main`, we simply merge commit all of them. no squashes.

**Pull request merged**
