### PR TITLE
feat(backend): inherit from AbstractBaseUser and add login and register API endpoints

### PR DESCRIPTION
**Pull request by MucahitErdoganUnlu**

### CODE REVIEW

**Comment by Meminseeker** [comment]
Your PR is to the branch `main`. It should be the branch `develop`. As a best practice, we do not merge our codes to main before testing them thoroughly in the `develop` branch.

**Comment by MucahitErdoganUnlu** [comment]
Thank you @Meminseeker ! I changed the base to `develop`

**Comment by Meminseeker** [comment]
I run the tests, all are passing.
I added a user through `/user/signup` endpoint. It works.
I tried to sign in through `/user/login` endpoint. It also works. I received the token 👌

Now it is time to test it on the docker.

**Comment by Meminseeker** [comment]
It works on Docker, too. Perfect. I'm approving it

**Pull request merged**
