### PR TITLE
feat(client): multistep quiz creation

### LINKED ISSUE #765: Use SWR for component-scoped data fetching
# 🧱 Description

Loaders are route, scoped. Some of the functionality depends on the components. For instance quiz creation: each question component should fetch the tagging api.

## 📋 Acceptance Criteria

- [ ] [swr](https://swr.vercel.app/) is installed and used for component data fetching.

### PR DESCRIPTION
**Pull request by umitcan07**
closes #765 , #766 , #728

### CODE REVIEW

**Comment by umitcan07** [comment]
https://github.com/user-attachments/assets/2f97fc9c-c9ce-4a4f-81f1-7d7be757e74b

almost there!

the shit is complex as hell

**Comment by umitcan07** [comment]
CleanShot 2024-12-14 at 00 59 53@2x

**Comment by umitcan07** [comment]
CleanShot 2024-12-14 at 01 56 00@2x

**Comment by umitcan07** [comment]
CleanShot 2024-12-14 at 02 19 24@2x

**Comment by umitcan07** [comment]
CleanShot 2024-12-14 at 02 54 18@2x

no confusions allowed :)

**Comment by umitcan07** [comment]
CleanShot 2024-12-14 at 03 24 58@2x
more validation, better UX

**Comment by umitcan07** [comment]
CleanShot 2024-12-14 at 03 39 35@2x

this shit is FUN

**Comment by umitcan07** [comment]
CleanShot 2024-12-14 at 05 29 57@2x

CREATED FULLY ON CLIENT.

now the only things thats missing is hints really

**Comment by umitcan07** [comment]
CleanShot 2024-12-14 at 05 34 58@2x

current view

**Comment by umitcan07** [comment]
CleanShot 2024-12-14 at 05 43 04@2x

We'r more defensive...

**Comment by umitcan07** [comment]
CleanShot 2024-12-14 at 06 32 17@2x

the valiation info box (on the top right corner) is sticky to the top, in case there're too much vertical space.

**Comment by umitcan07** [comment]
CleanShot 2024-12-14 at 06 41 21@2x

New: The current page [ 1/2 or 2/2 ] next to the sub-heading

**Comment by umitcan07** [comment]
CleanShot 2024-12-14 at 20 59 44@2x

CleanShot 2024-12-14 at 21 00 06@2x

**Comment by umitcan07** [comment]
READY.
LFGGGGG

**Comment by umitcan07** [comment]
CleanShot 2024-12-14 at 21 40 25@2x

CleanShot 2024-12-14 at 21 40 40@2x

CleanShot 2024-12-14 at 21 40 46@2x

CleanShot 2024-12-14 at 21 40 30@2x


CleanShot 2024-12-14 at 21 41 19@2x

**Review by hks1444 — APPROVED** [review]

**Review by MucahitErdoganUnlu — APPROVED** [review]
excellent work

**Comment by umitcan07** [comment]
READY.

**Pull request merged**
