### PR TITLE
lab: work done for lab7 & forum integration

### PR DESCRIPTION
**Pull request by umitcan07**

### CODE REVIEW

**Comment by hks1444** [comment]
## User Experience Decisions
- We decided to make our web application keyboard-navigable to make it more accessible to disabled people. The forum post-creation interface was implemented in the previous lab and made keyboard-navigable.
- Our web application has a responsive design that allows users to open the application via their mobile phone's browser and use the app just like on a desktop computer or laptop.
- We decided to implement a hint structure for the quizzes. We thought that the users would be frustrated if they encountered a quiz question that they did not know the answer to since there was no way to get a hint in the previous version.
- We added aria labels to our components to make voice-over read the page correctly. This does not improve the visual experience but it lets blind users using our app.

**Comment by ArdaVural** [comment]
A detailed software quality plan is documented.
Unit test coverage goals are clearly defined.
Strategy for integration testing is outlined, including tools.
#650 
Worked on it with @MucahitErdoganUnlu @ceydanursen

**Comment by yunuskaydin** [comment]
[Lab report](https://github.com/bounswe/bounswe2024group11/wiki/Lab-Report-%237) is created.
#649

**Comment by ceydanursen** [comment]
Issues:
#648 

Commits:
81a88471cc13b07fbdd027920ebb571ebb2498e3

**Comment by meminciftci** [comment]
* Task: Plan for the demo next week, including data population strategy, scenario, etc.
* Issue: [here](https://github.com/bounswe/bounswe2024group11/issues/647)
* WikiPage: [here](https://github.com/bounswe/bounswe2024group11/wiki/Milestone-2-Demo-Plan)
* Assignees: @meminciftci @ozankrkya

**Comment by meminciftci** [comment]
* Task: Resolve corse issue when connecting client and backend servers. 
* Issue: [here](https://github.com/bounswe/bounswe2024group11/issues/651)
* Assignees: @ozankrkya @umitcan07

**Comment by MucahitErdoganUnlu** [comment]
#652 , 433e59de6b70f749f8487c74fab4ff9a61fb4d57

**Comment by umitcan07** [comment]
CleanShot 2024-11-20 at 01 51 08@2x

- Forum Pagination
- Forum Upvote/Downvote/Bookmark Actions
- Cookie + ApiClient (Axios)
- Massive refactors on router / file structure.

**Review by MucahitErdoganUnlu — APPROVED** [review]

**Pull request merged**
