### PR TITLE
w3c(client): apply standards initiatives

### PR DESCRIPTION
**Pull request by hks1444**
1. Standard selection and documentation:
  1.1. Document the standard in the wiki as to:
    1.1.1. what is it for, its benefits,
    1.1.2. what are the requirements of following the standard,
    1.1.3. how it will be enforced in practice.
2. Substantial commit(s) regarding the selected standard,
3. ⁠Substantial commit(s) regarding domain specificity.

### CODE REVIEW

**Comment by MucahitErdoganUnlu** [comment]
## Domain Specific Commits
*

**Comment by Meminseeker** [comment]
## Substantial commit(s) regarding the selected standard:

1.

**Comment by Meminseeker** [comment]
## Issues created during this lab:

1. [Document WCAG 2.1 Standards](https://github.com/bounswe/bounswe2024group11/issues/596)
2. [Document WAI-ARIA 1.2 Standards for Accessibility Compliance](https://github.com/bounswe/bounswe2024group11/issues/597)
3. [Implement Leaderboard Screens for Mobile Application](https://github.com/bounswe/bounswe2024group11/issues/598)
4. [Fix Radio Button for Quiz Sorting (W3C ARIA)](https://github.com/bounswe/bounswe2024group11/issues/599)
5. [Document SVG 2 Standards](https://github.com/bounswe/bounswe2024group11/issues/600)
6. [Implement Quiz Screens for Mobile](https://github.com/bounswe/bounswe2024group11/issues/601)

**Comment by ozankrkya** [comment]
## Documentations created during this lab: 
1. [Auto Point-Assignment Mechanism for Quiz Creation](https://github.com/bounswe/bounswe2024group11/wiki/Point-Assignment-Mechanism-for-Created-Quizzes)

**Pull request merged**
